version: "3.8"

services:
  migrate:
    build:
      context: ../
      dockerfile: dockerfiles/migrate/Dockerfile
    container_name: cargonex_migrate
    env_file:
      - ../dev/.env
    networks:
      - cargonex_network

networks:
  cargonex_network:
    external: true
